// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkIRjMnTFjeLKZqphpdUKWAB3lpgUIs2Y',
    appId: '1:365212580774:web:07b6766058195d92976d67',
    messagingSenderId: '365212580774',
    projectId: 'tacos-4c205',
    authDomain: 'tacos-4c205.firebaseapp.com',
    storageBucket: 'tacos-4c205.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqrbb9FpZzMmluwTb9-6RfKR48nGmGSE',
    appId: '1:365212580774:android:008cb61c33e2bb15976d67',
    messagingSenderId: '365212580774',
    projectId: 'tacos-4c205',
    storageBucket: 'tacos-4c205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kausBru43FjVUzXRc8BhbhTRMfN-k6Y',
    appId: '1:365212580774:ios:f81825e4e82986ab976d67',
    messagingSenderId: '365212580774',
    projectId: 'tacos-4c205',
    storageBucket: 'tacos-4c205.appspot.com',
    iosBundleId: 'com.example.tacos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kausBru43FjVUzXRc8BhbhTRMfN-k6Y',
    appId: '1:365212580774:ios:f81825e4e82986ab976d67',
    messagingSenderId: '365212580774',
    projectId: 'tacos-4c205',
    storageBucket: 'tacos-4c205.appspot.com',
    iosBundleId: 'com.example.tacos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkIRjMnTFjeLKZqphpdUKWAB3lpgUIs2Y',
    appId: '1:365212580774:web:cb6ee04d42715083976d67',
    messagingSenderId: '365212580774',
    projectId: 'tacos-4c205',
    authDomain: 'tacos-4c205.firebaseapp.com',
    storageBucket: 'tacos-4c205.appspot.com',
  );
}
